version: 2
jobs:

  deploy:
    working_directory: ~/pwa
    docker:
      - image: makki0205/deploy

    steps:
      - checkout
      - run:
          name: aws login
          command: make aws/credentials
      - run:
          name: deploy
          command: make aws/deploy

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master